# Generated by Django 3.1.7 on 2021-02-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spam',
            field=models.IntegerField(default=0),
        ),
    ]
